filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    processors:
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
      index: "kubernetes-%{+yyyy.MM.dd.HH}"
      pipeline: ""

elasticsearch:
  hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
  ssl:
    enabled: false

secretMounts: []

# Ensure TLS is disabled at global chart level
ssl:
  enabled: false

# Ensure Filebeat doesn't look for cert secrets
extraVolumes: []
extraVolumeMounts: []

setup:
  kibana:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
