filebeat:
  fullnameOverride: "filebeat"
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log

      output.elasticsearch:
        hosts: ["http://opensearch.logging.svc.cluster.local:9200"]
        username: "admin"
        password: "admin"
        ssl.enabled: false

  extraVolumes: []
  extraVolumeMounts: []

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
