filebeat:
  fullnameOverride: "filebeat"

  # Disable internal Elasticsearch and Kibana references
  elasticsearch:
    enabled: false

  kibana:
    enabled: false

  # Explicitly disable all setup steps that look for certificates
  setup:
    kibana:
      enabled: false
    ilm:
      enabled: false

  # Absolutely disable any cert secret mounts
  secretMounts: []

  # Your filebeat.yml output to opensearch
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log

      output.elasticsearch:
        hosts: ["http://opensearch.logging.svc.cluster.local:9200"]
        ssl.enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
