filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    processors:
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
      protocol: "http"
      ssl.enabled: false
      ssl.verification_mode: none
      username: ""
      password: ""

elasticsearch:
  hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
  ssl:
    enabled: false

secretMounts: []
extraVolumes: []
extraVolumeMounts: []

ssl:
  enabled: false

# Disable setting up any certs
certs: {}

setup:
  kibana:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
