filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    processors:
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
      index: "kubernetes-%{+yyyy.MM.dd.HH}"
      pipeline: ""

elasticsearch:
  ssl:
    enabled: false
  hosts: ["http://opensearch-cluster-master.logging.svc.cluster.local:9200"]
  protocol: "http"

secretMounts: []

setup:
  kibana:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 110m
    memory: 256Mi
