apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.12.0
        ports:
          - containerPort: 9200
        env:
          - name: discovery.type
            value: "single-node"
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"
          - name: DISABLE_SECURITY_PLUGIN
            value: "true"
          - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
            value: "true"
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms128m -Xmx128m"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "768Mi"
            cpu: "800m"
