opensearch:
  fullnameOverride: "opensearch"
  clusterName: "opensearch-cluster"
  nodeGroup: "single-node"
  replicas: 1

  roles:
    - master
    - ingest
    - data

  opensearchJavaOpts: "-Xms512m -Xmx512m"

  persistence:
    enabled: true
    size: 2Gi
    storageClass: "local-path"

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "800m"
      memory: "768Mi"

  extraEnvs:
    - name: discovery.type
      value: "single-node"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
      value: "true"

  securityConfig:
    enabled: false
  security:
    enabled: false

  service:
    type: NodePort
    port: 9200
    nodePort: 30920

  # Optional: safer health checks so ArgoCD / K8s doesn't kill too early
  startupProbe:
    tcpSocket:
      port: 9200
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 60

  readinessProbe:
    tcpSocket:
      port: 9200
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 10
