clusterName: "opensearch-cluster"

master:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "local-path"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 300m
      memory: 1Gi
  extraEnvs:
    - name: discovery.type
      value: "single-node"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
      value: "true"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"

data:
  replicas: 0

ingest:
  replicas: 0

coordinating:
  replicas: 0

plugins:
  install: []

service:
  type: NodePort
  port: 9200
  nodePort: 30920

securityConfig:
  enabled: false
security:
  enabled: false
