replicas: 1

nodeGroup: default

nodes:
  default:
    replicas: 1
    roles:
      master: true
      ingest: true
      data: true
      remote_cluster_client: false
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 1Gi

persistence:
  enabled: true
  size: 2Gi
  storageClass: local-path

securityConfig:
  enabled: false

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "admin"

opensearchJavaOpts: "-Xmx512M -Xms512M"

service:
  type: NodePort
  port: 9200
  nodePort: 30920

indexManagement:
  enabled: true
  policies:
    - policyId: delete-after-2h
      description: "Delete logs after 2 hours"
      schema:
        policy:
          description: "delete after 2h"
          default_state: "delete"
          states:
            - name: "delete"
              actions:
                - delete:
                    delete_searchable_snapshot: true
              transitions: []
