fullnameOverride: "opensearch"

clusterName: "opensearch-cluster"
nodeGroup: "single-node"
roles:
  - master
  - data
  - ingest

replicas: 1

persistence:
  enabled: true
  size: 2Gi
  storageClass: "local-path"

opensearchJavaOpts: "-Xmx512M -Xms512M"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi

# 🔥 Important: set discovery.type directly to skip cluster discovery
extraEnvs:
  - name: discovery.type
    value: "single-node"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"
  - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
    value: "true"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "no-password-needed"  # just set anything so it doesn't complain

securityConfig:
  enabled: false
security:
  enabled: false

plugins:
  install: []  # ensure no extra plugins

service:
  type: NodePort
  port: 9200
  nodePort: 30920

indexManagement:
  enabled: false
