replicas: 1

# Ensure ALL nodes use same small resources
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1Gi

persistence:
  enabled: true
  size: 2Gi
  storageClass: local-path

# Disables security plugin
securityConfig:
  enabled: false

# JVM heap small
opensearchJavaOpts: "-Xmx512M -Xms512M"

# Only deploy one type of node to keep ultra-light
roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "false"

nodeGroup: single-node

# No dashboards deployed here to keep lighter (deploy separately if needed)
dashboards:
  enabled: false

service:
  type: NodePort
  port: 9200
  nodePort: 30920

# Index policy to delete after 2 hours
indexManagement:
  enabled: true
  policies:
    - policyId: delete-after-2h
      description: "Delete logs after 2 hours"
      schema:
        policy:
          description: "delete after 2h"
          default_state: "delete"
          states:
            - name: "delete"
              actions:
                - delete:
                    delete_searchable_snapshot: true
              transitions: []
