opensearch:
  fullnameOverride: "opensearch"

  clusterName: "opensearch-cluster"
  nodeGroup: "single-node"
  replicas: 1
  roles:
    - master
    - ingest
    - data

  plugins:
    install: []  # no plugins, super minimal

  persistence:
    enabled: true
    size: 2Gi
    storageClass: "local-path"

  opensearchJavaOpts: "-Xmx512M -Xms512M"

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 300m
      memory: 1Gi

  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "Opensearch123"

  securityConfig:
    enabled: false
  security:
    enabled: false

  service:
    type: NodePort
    port: 9200
    nodePort: 30920

  indexManagement:
    enabled: true
    policies:
      - policyId: delete-after-2h
        description: "Delete logs after 2 hours"
        schema:
          policy:
            description: "delete after 2h"
            default_state: "delete"
            states:
              - name: "delete"
                actions:
                  - delete:
                      delete_searchable_snapshot: true
                transitions: []
